const DEV_CARDS = Object.freeze({
    KNIGHT: "knight",
    ROAD_BUILDING: "road_building",
    INVENTION: "invention",
    MONOPOLY: "monopoly",
    VICTORY_POINT: "victory_point"
});

const BASE_DEV_CARDS = [
    DEV_CARDS.KNIGHT,
    DEV_CARDS.KNIGHT,
    DEV_CARDS.KNIGHT,
    DEV_CARDS.KNIGHT,
    DEV_CARDS.KNIGHT,
    DEV_CARDS.KNIGHT,
    DEV_CARDS.KNIGHT,
    DEV_CARDS.KNIGHT,
    DEV_CARDS.KNIGHT,
    DEV_CARDS.KNIGHT,
    DEV_CARDS.KNIGHT,
    DEV_CARDS.KNIGHT,
    DEV_CARDS.KNIGHT,
    DEV_CARDS.KNIGHT,

    DEV_CARDS.ROAD_BUILDING,
    DEV_CARDS.ROAD_BUILDING,

    DEV_CARDS.INVENTION,
    DEV_CARDS.INVENTION,

    DEV_CARDS.MONOPOLY,
    DEV_CARDS.MONOPOLY,

    DEV_CARDS.VICTORY_POINT,
    DEV_CARDS.VICTORY_POINT,
    DEV_CARDS.VICTORY_POINT,
    DEV_CARDS.VICTORY_POINT,
    DEV_CARDS.VICTORY_POINT
];

module.exports = {
    DEV_CARDS,
    BASE_DEV_CARDS
};