const BASE_TOKENS = [
    2, 3, 3, 4, 4, 5, 5,
    6, 6, 8, 8, 9, 9, 10, 10,
    11, 11, 12
];

const HYBRID_EXTRA_TOKENS = [
    3, 4, 5, 9, 10, 11
];

const EXPANSION_EXTRA_TOKENS = [
    2, 3, 6, 8, 12
];

const EXTRA_UNIFORM_DISTRIBUTION = [
    6, 8, 5, 9, 4, 10, 3, 11, 2, 12
];

const ALL_TOKENS = [
    ...BASE_TOKENS,
    ...HYBRID_EXTRA_TOKENS,
    ...EXPANSION_EXTRA_TOKENS,
    ...EXTRA_UNIFORM_DISTRIBUTION,
    ...EXTRA_UNIFORM_DISTRIBUTION,
    ...EXTRA_UNIFORM_DISTRIBUTION,
    ...EXTRA_UNIFORM_DISTRIBUTION,
    ...EXTRA_UNIFORM_DISTRIBUTION,
    ...EXTRA_UNIFORM_DISTRIBUTION
];

module.exports = {
    BASE_TOKENS,
    HYBRID_EXTRA_TOKENS,
    EXPANSION_EXTRA_TOKENS,
    EXTRA_UNIFORM_DISTRIBUTION,
    ALL_TOKENS
};